{% set name = "dictdiffer" %}
{% set version = "0.9.0" %}
{% set sha256 = "17bacf5fbfe613ccf1b6d512bd766e6b21fb798822a133aa86098b8ac9997578" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner >=2.7
    - setuptools_scm >=3.1
  run:
    - python >={{ python_min }}

test:
  requires:
    - setuptools
    - python {{ python_min }}
  imports:
    - dictdiffer

about:
  home: https://github.com/inveniosoftware/dictdiffer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dictdiffer is a library that helps you to diff and patch dictionaries.
  doc_url: https://dictdiffer.readthedocs.io
  dev_url: https://github.com/inveniosoftware/dictdiffer

extra:
  recipe-maintainers:
    - hodgsonw
    - kmuehlbauer
    - maresb
