{% set name = "dictdiffer" %}
{% set version = "0.8.0" %}
{% set sha256 = "b3ad476fc9cca60302b52c50e1839342d2092aeaba586d69cbf9249f87f52463" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - pytest-runner >=2.7
  run:
    - python

test:
  requires:
    - setuptools
  imports:
    - dictdiffer

about:
  home: https://github.com/inveniosoftware/dictdiffer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dictdiffer is a library that helps you to diff and patch dictionaries.
  doc_url: https://dictdiffer.readthedocs.io
  dev_url: https://github.com/inveniosoftware/dictdiffer

extra:
  recipe-maintainers:
    - hodgsonw
    - kmuehlbauer
